/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import helpers.CadastroManager;
import model.bean.Venda;
import model.dao.VendaDAO;

/**
 *
 * @author horaciocome1
 * esta classe recebe uma venda
 * faz uma apresentacao resumida
 * pede ao utilizador para confirmar
 * recebe uma nota sobre a venda
 * e manda ao banco
 */
public class ConfirmarVenda extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     * Que sera utilizado para exibir a lista de produtos como confirmacao final antes de salvar no banco.
     */
    
    private static Venda venda;
    private CadastroManager cadManager;
    
    public ConfirmarVenda(Venda venda) {
        initComponents();
        ConfirmarVenda.venda = venda;
        cadManager = new CadastroManager();
        txtCesto.setText(cadManager.vendaToText(venda));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtCesto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();
        btConfirmar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Confirmação de Venda");
        setAlwaysOnTop(true);

        txtCesto.setEditable(false);
        txtCesto.setColumns(20);
        txtCesto.setLineWrap(true);
        txtCesto.setRows(5);
        txtCesto.setToolTipText("Neste campo podera ver a lista de produtos que o cliente pretende comprar e suas respectvvas quantidades. Observe com cautela e confirme a venda.");
        txtCesto.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtCesto);

        txtNota.setColumns(20);
        txtNota.setLineWrap(true);
        txtNota.setRows(5);
        txtNota.setText("Pode adicionar uma nota sobre a venda aqui...");
        txtNota.setToolTipText("Este campo lhe permite adicionar um comentario ou nota a venda. Util para se lembrar de termos acordados em caso de vale/divida.");
        txtNota.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtNota);

        btConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_check_black_18dp.png"))); // NOI18N
        btConfirmar.setToolTipText("Confirmar venda. So clique depois de ter a certeza que esta tudo nos conformes.");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_chevron_left_black_18dp.png"))); // NOI18N
        btVoltar.setToolTipText("Volltar e editar.");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConfirmar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btConfirmar)
                    .addComponent(btVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        // TODO add your handling code here:
        if (!ConfirmarVenda.venda.isEstado() 
                && txtNota.getText().equalsIgnoreCase("Pode adicionar uma nota sobre a venda aqui...")) {
            Alerta alerta = new Alerta("Neste tipo de venda é importante adicionar uma nota.");
            alerta.setVisible(true);
        } else {
            ConfirmarVenda.venda.setNota(txtNota.getText());
            this.dispose();
            VendaDAO dao = new VendaDAO();
            dao.add(ConfirmarVenda.venda);
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarVenda(venda).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCesto;
    private javax.swing.JTextArea txtNota;
    // End of variables declaration//GEN-END:variables
}
