/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import helpers.CadastroManager;
import helpers.PanelManager;
import helpers.TableManager;
import model.dao.ProdutoDAO;

/**
 *
 * @author horaciocome1
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     * 
     * 20180212
     * ja se cadastra produto
     * vem-se os produtos disponiveis
     * faz se uma busca pelo nome entre os produtos
     * e apaga-se produto
     * 
     * 20180213
     * ja se edita produto
     * o proximo passo eh poder cadastrar um stock, a partir dos produtos cadastrados
     * deve permitir cadastrar um stock
     * ao fazer isso deve se adicionar a quantidade guevada nos respectivos produtos
     * so se edita um stock intacto ou seja, que cada produto ainda tenha disponivel a quantidade adicionada
     * o relacionamento eh de muitos pra muitos
     * 
     */
    
    public Inicio() {
        initComponents();
        // este code devera passar para a chamada do painel Produto
        TableManager tm = new TableManager();
        tm.updateProdutos(tbProduto, txtSearchProduto.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeftMenu = new javax.swing.JPanel();
        btHome = new javax.swing.JButton();
        btProduto = new javax.swing.JButton();
        btStock = new javax.swing.JButton();
        btVenda = new javax.swing.JButton();
        panelParent = new javax.swing.JPanel();
        panelProduto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduto = new javax.swing.JTable();
        panelParentProduto = new javax.swing.JPanel();
        panelDetalheProduto = new javax.swing.JPanel();
        btCadProduto = new javax.swing.JButton();
        btEditProduto = new javax.swing.JButton();
        btDelProduto = new javax.swing.JButton();
        lblImgProduto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblProdutoQtd = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblProdutoDesc00 = new javax.swing.JLabel();
        lblProdutoDesc01 = new javax.swing.JLabel();
        lblProdutoDesc02 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblProdutoPreco = new javax.swing.JLabel();
        panelCadastroProduto = new javax.swing.JPanel();
        btCancelProduto = new javax.swing.JButton();
        btSaveProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtPrecoGueva = new javax.swing.JTextField();
        txtPrecoVenda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSearchProduto = new javax.swing.JTextField();
        panelStock = new javax.swing.JPanel();
        panelStocks = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableStock = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtStockProdutos = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        txtProcuraStockProdutos = new javax.swing.JTextField();
        panelDetalheStock = new javax.swing.JPanel();
        btCadStock = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblLucroStock = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblRTStock = new javax.swing.JLabel();
        lblQtdProduto = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        panelBottom = new javax.swing.JPanel();
        lblBottomLog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caderninho");
        setResizable(false);

        panelLeftMenu.setBackground(new java.awt.Color(200, 200, 200));
        panelLeftMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        btHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_home_black_18dp.png"))); // NOI18N
        btHome.setToolTipText("Início");

        btProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_filter_vintage_black_18dp_1.png"))); // NOI18N
        btProduto.setToolTipText("Produtos");

        btStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_archive_black_18dp.png"))); // NOI18N
        btStock.setToolTipText("Stocks");

        btVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_shopping_cart_black_18dp.png"))); // NOI18N
        btVenda.setToolTipText("Vendas");

        javax.swing.GroupLayout panelLeftMenuLayout = new javax.swing.GroupLayout(panelLeftMenu);
        panelLeftMenu.setLayout(panelLeftMenuLayout);
        panelLeftMenuLayout.setHorizontalGroup(
            panelLeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btHome)
            .addComponent(btProduto)
            .addComponent(btStock)
            .addComponent(btVenda)
        );
        panelLeftMenuLayout.setVerticalGroup(
            panelLeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftMenuLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelParent.setLayout(new java.awt.CardLayout());

        tbProduto.setBackground(new java.awt.Color(239, 240, 241));
        tbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "_id", "Produto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProduto.setToolTipText("Produtos cadastrados no sistema.");
        tbProduto.setGridColor(new java.awt.Color(213, 213, 213));
        tbProduto.setShowVerticalLines(false);
        tbProduto.getTableHeader().setReorderingAllowed(false);
        tbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdutoMouseClicked(evt);
            }
        });
        tbProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbProduto);
        if (tbProduto.getColumnModel().getColumnCount() > 0) {
            tbProduto.getColumnModel().getColumn(0).setMaxWidth(60);
            tbProduto.getColumnModel().getColumn(1).setResizable(false);
        }

        panelParentProduto.setLayout(new java.awt.CardLayout());

        btCadProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_add_black_18dp.png"))); // NOI18N
        btCadProduto.setToolTipText("Cadastrar um novo produto.");
        btCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadProdutoActionPerformed(evt);
            }
        });

        btEditProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_mode_edit_black_18dp.png"))); // NOI18N
        btEditProduto.setToolTipText("Editar este produto.");
        btEditProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditProdutoActionPerformed(evt);
            }
        });

        btDelProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_delete_forever_black_18dp.png"))); // NOI18N
        btDelProduto.setToolTipText("Eliminar este produto.");
        btDelProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelProdutoActionPerformed(evt);
            }
        });

        lblImgProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/amazing-beautiful-love-quotes-wallpapers-pics-images-photos-19.jpg"))); // NOI18N
        lblImgProduto.setToolTipText("Imagem descritiva.");
        lblImgProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setLabelFor(lblProduto);
        jLabel2.setText("Produto:");

        lblProduto.setText("Fonte da vida, 5L de água");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setLabelFor(lblProdutoQtd);
        jLabel4.setText("Quantidade disponível:");

        lblProdutoQtd.setText("40 unidades");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setLabelFor(lblProdutoDesc00);
        jLabel6.setText("Descrição:");

        lblProdutoDesc00.setText("Esta deveria ser uma breve descrição das");

        lblProdutoDesc01.setText("carecterísticas deste produto, ou de seus");

        lblProdutoDesc02.setText("critérios de venda.");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setLabelFor(lblProdutoPreco);
        jLabel10.setText("Preços (gueva/venda) por unidade:");

        lblProdutoPreco.setText("42.5 MT / 50.0 MT");

        javax.swing.GroupLayout panelDetalheProdutoLayout = new javax.swing.GroupLayout(panelDetalheProduto);
        panelDetalheProduto.setLayout(panelDetalheProdutoLayout);
        panelDetalheProdutoLayout.setHorizontalGroup(
            panelDetalheProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalheProdutoLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(lblImgProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDetalheProdutoLayout.createSequentialGroup()
                .addGroup(panelDetalheProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalheProdutoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProdutoDesc02, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetalheProdutoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDetalheProdutoLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblProdutoQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDetalheProdutoLayout.createSequentialGroup()
                        .addGroup(panelDetalheProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDetalheProdutoLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelDetalheProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProdutoDesc00, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblProdutoDesc01, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelDetalheProdutoLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDetalheProdutoLayout.createSequentialGroup()
                        .addComponent(btCadProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEditProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDelProduto)))
                .addContainerGap())
        );
        panelDetalheProdutoLayout.setVerticalGroup(
            panelDetalheProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalheProdutoLayout.createSequentialGroup()
                .addGroup(panelDetalheProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCadProduto)
                    .addComponent(btEditProduto)
                    .addComponent(btDelProduto))
                .addGap(21, 21, 21)
                .addComponent(lblImgProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDetalheProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblProduto))
                .addGap(18, 18, 18)
                .addGroup(panelDetalheProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblProdutoQtd))
                .addGap(18, 18, 18)
                .addGroup(panelDetalheProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblProdutoDesc00))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProdutoDesc01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProdutoDesc02)
                .addGap(18, 18, 18)
                .addGroup(panelDetalheProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblProdutoPreco))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        panelParentProduto.add(panelDetalheProduto, "card3");

        btCancelProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_clear_black_18dp.png"))); // NOI18N
        btCancelProduto.setToolTipText("Limpar e fechar.");
        btCancelProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelProdutoActionPerformed(evt);
            }
        });

        btSaveProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_save_black_18dp.png"))); // NOI18N
        btSaveProduto.setToolTipText("Guardar.");
        btSaveProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveProdutoActionPerformed(evt);
            }
        });

        jLabel1.setLabelFor(txtProduto);
        jLabel1.setText("Produto:");
        jLabel1.setToolTipText("Insira o nome correspondente ao produto em questão");

        txtProduto.setText("Tomate Verde Pequeno");

        jLabel3.setLabelFor(txtDesc);
        jLabel3.setText("Descrição:");

        txtDesc.setColumns(20);
        txtDesc.setLineWrap(true);
        txtDesc.setRows(5);
        txtDesc.setText("Bom tomate, fresco, da baixa do Mulauze. Vendido em grupos de quatro tomates.");
        txtDesc.setToolTipText("Insira os detalhes do produto que pretende cadastrar. Bem como, se preferir, detalhes sobre como a venda deste produto se realiza.");
        txtDesc.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtDesc);

        jLabel5.setLabelFor(txtPrecoGueva);
        jLabel5.setText("Preço de gueva (MT):");

        txtPrecoGueva.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPrecoGueva.setText("16.5");
        txtPrecoGueva.setToolTipText("Insira quanto paga para adquirir a unidade deste produto. Tens inserir neste formato \"16.5\".");

        txtPrecoVenda.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPrecoVenda.setText("20.0");
        txtPrecoVenda.setToolTipText("Insira quanto cobra para vender a unidade deste produto. Tens inserir neste formato \"16.5\".");

        jLabel7.setLabelFor(txtPrecoVenda);
        jLabel7.setText("Preço de venda (MT):");

        jLabel8.setText("Note o botão, superior direito, grava as alterações directamente. Ou seja, ao clicar nele, será assumido que");

        jLabel9.setText("todos os campos estão conforme a sua vontade e não será exibido um diálogo de confirmação. Caso não");

        jLabel11.setText("tenha especificado o preço não poderá gravar. Assegure-se de não deixar campos nulos.");

        javax.swing.GroupLayout panelCadastroProdutoLayout = new javax.swing.GroupLayout(panelCadastroProduto);
        panelCadastroProduto.setLayout(panelCadastroProdutoLayout);
        panelCadastroProdutoLayout.setHorizontalGroup(
            panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroProdutoLayout.createSequentialGroup()
                .addGroup(panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroProdutoLayout.createSequentialGroup()
                        .addComponent(btCancelProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSaveProduto))
                    .addComponent(txtProduto)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastroProdutoLayout.createSequentialGroup()
                        .addGroup(panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecoGueva, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(panelCadastroProdutoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCadastroProdutoLayout.setVerticalGroup(
            panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroProdutoLayout.createSequentialGroup()
                .addGroup(panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCancelProduto)
                    .addComponent(btSaveProduto))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecoGueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelParentProduto.add(panelCadastroProduto, "card2");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_search_black_18dp.png"))); // NOI18N
        jLabel12.setLabelFor(txtSearchProduto);

        txtSearchProduto.setToolTipText("Use este campo para filtrar dentre os produtos cadastrados.");
        txtSearchProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchProdutoActionPerformed(evt);
            }
        });
        txtSearchProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchProdutoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelProdutoLayout = new javax.swing.GroupLayout(panelProduto);
        panelProduto.setLayout(panelProdutoLayout);
        panelProdutoLayout.setHorizontalGroup(
            panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutoLayout.createSequentialGroup()
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProdutoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelParentProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProdutoLayout.setVerticalGroup(
            panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelParentProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelProdutoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtSearchProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelParent.add(panelProduto, "card2");

        tableStock.setBackground(new java.awt.Color(239, 240, 241));
        tableStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "_id", "data", "custo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableStock.setGridColor(new java.awt.Color(213, 213, 213));
        tableStock.setShowVerticalLines(false);
        jScrollPane3.setViewportView(tableStock);
        if (tableStock.getColumnModel().getColumnCount() > 0) {
            tableStock.getColumnModel().getColumn(0).setMaxWidth(60);
            tableStock.getColumnModel().getColumn(1).setResizable(false);
            tableStock.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        txtStockProdutos.setColumns(20);
        txtStockProdutos.setRows(5);
        jScrollPane4.setViewportView(txtStockProdutos);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_search_black_18dp.png"))); // NOI18N

        txtProcuraStockProdutos.setText("jTextField1");

        javax.swing.GroupLayout panelStocksLayout = new javax.swing.GroupLayout(panelStocks);
        panelStocks.setLayout(panelStocksLayout);
        panelStocksLayout.setHorizontalGroup(
            panelStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStocksLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStocksLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProcuraStockProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelStocksLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))))
        );
        panelStocksLayout.setVerticalGroup(
            panelStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(panelStocksLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProcuraStockProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btCadStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_add_black_18dp.png"))); // NOI18N

        jLabel14.setText("Produtos adquiridos:");

        jLabel15.setText("Lucro esperado (MT):");

        lblLucroStock.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLucroStock.setText("314.0");

        jLabel17.setText("Receita esperada (MT):");

        lblRTStock.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRTStock.setText("1502.0");

        lblQtdProduto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblQtdProduto.setText("13");

        jLabel20.setForeground(new java.awt.Color(82, 82, 82));
        jLabel20.setText("Ao clicar no botão superior,");

        jLabel21.setForeground(new java.awt.Color(82, 82, 82));
        jLabel21.setText("lhe será apresentada uma tela em");

        jLabel22.setForeground(new java.awt.Color(82, 82, 82));
        jLabel22.setText("que sequencialmente, irá introduzir");

        jLabel23.setForeground(new java.awt.Color(82, 82, 82));
        jLabel23.setText("a quantidade guevada de cada");

        jLabel24.setForeground(new java.awt.Color(82, 82, 82));
        jLabel24.setText("produto cadastrado no sistema");

        javax.swing.GroupLayout panelDetalheStockLayout = new javax.swing.GroupLayout(panelDetalheStock);
        panelDetalheStock.setLayout(panelDetalheStockLayout);
        panelDetalheStockLayout.setHorizontalGroup(
            panelDetalheStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalheStockLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCadStock))
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblRTStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLucroStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblQtdProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDetalheStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalheStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDetalheStockLayout.setVerticalGroup(
            panelDetalheStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalheStockLayout.createSequentialGroup()
                .addComponent(btCadStock)
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQtdProduto)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLucroStock)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRTStock)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelStockLayout = new javax.swing.GroupLayout(panelStock);
        panelStock.setLayout(panelStockLayout);
        panelStockLayout.setHorizontalGroup(
            panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStockLayout.createSequentialGroup()
                .addComponent(panelStocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDetalheStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelStockLayout.setVerticalGroup(
            panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelStocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDetalheStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelParent.add(panelStock, "card3");

        panelBottom.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 2, 10));

        lblBottomLog.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBottomLog.setLabelFor(panelBottom);
        lblBottomLog.setText("Aqui existirá uma mensagem com informação útil.");

        javax.swing.GroupLayout panelBottomLayout = new javax.swing.GroupLayout(panelBottom);
        panelBottom.setLayout(panelBottomLayout);
        panelBottomLayout.setHorizontalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBottomLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBottomLayout.setVerticalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBottomLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBottomLog))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLeftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeftMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadProdutoActionPerformed
        // TODO add your handling code here:
        PanelManager pm = new PanelManager();
        pm.loadPanel(panelParentProduto, panelCadastroProduto);
    }//GEN-LAST:event_btCadProdutoActionPerformed

    private void btCancelProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelProdutoActionPerformed
        // TODO add your handling code here:
        txtProduto.setText("");
        txtDesc.setText("");
        txtPrecoGueva.setText("");
        txtPrecoVenda.setText("");
        PanelManager pm = new PanelManager();
        pm.loadPanel(panelParentProduto, panelDetalheProduto);
        if (!tbProduto.isEnabled())
            tbProduto.setEnabled(true);
    }//GEN-LAST:event_btCancelProdutoActionPerformed

    private void btSaveProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveProdutoActionPerformed
        // TODO add your handling code here:
        new CadastroManager().cadProduto(txtProduto, txtDesc, txtPrecoGueva, txtPrecoGueva, panelParentProduto, panelDetalheProduto,
                tbProduto); // passei os componentes e nao os valores para que a outra classe possa modifica-los
        // depois das alteracoes no banco, actualizo a tabela
        new TableManager().updateProdutos(tbProduto, txtSearchProduto.getText());
    }//GEN-LAST:event_btSaveProdutoActionPerformed

    private void tbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdutoMouseClicked
        // TODO add your handling code here:
        if (tbProduto.getSelectedRow() == -1) {
            // nenhuma linha da tabela seleccionada
        } else {
            int id = Integer.parseInt(tbProduto.getValueAt(tbProduto.getSelectedRow(), 0).toString());
            ProdutoDAO pdao = new ProdutoDAO();
            lblProduto.setText(pdao.getOne(id).getNome());
            lblProdutoPreco.setText(String.valueOf(pdao.getOne(id).getpCompra()) + " MT / " +
                    String.valueOf(pdao.getOne(id).getpVenda()) + " MT");
            // como utilizei 3 labels diferentes para a descricao, terei que fazer os arranjos abaixo
            String desc = pdao.getOne(id).getDesc();
            if (desc.length() < 46) {
                lblProdutoDesc00.setText(desc);
                lblProdutoDesc01.setText("");
                lblProdutoDesc02.setText("");
            } else if (desc.length() < 91) {
                lblProdutoDesc00.setText(desc.substring(0, 45));
                lblProdutoDesc01.setText(desc.substring(45));
                lblProdutoDesc02.setText("");
                
            } else {
                lblProdutoDesc00.setText(desc.substring(0, 45));
                lblProdutoDesc01.setText(desc.substring(45, 90));
                lblProdutoDesc02.setText(desc.substring(90));
                
            }
        }
        // para garantir uma funcionalidade semelhante enquanto o utilizador navega pela tabela atraves das setas,
        // farei uma redundancia no metodo para key released
    }//GEN-LAST:event_tbProdutoMouseClicked

    private void tbProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbProdutoKeyReleased
        // TODO add your handling code here:
        // redundancia do mouse click
        if (tbProduto.getSelectedRow() == -1) {
            // nenhuma linha da tabela seleccionada
        } else {
            int id = Integer.parseInt(tbProduto.getValueAt(tbProduto.getSelectedRow(), 0).toString());
            ProdutoDAO pdao = new ProdutoDAO();
            lblProduto.setText(pdao.getOne(id).getNome());
            lblProdutoPreco.setText(String.valueOf(pdao.getOne(id).getpCompra()) + " MT / " +
                    String.valueOf(pdao.getOne(id).getpVenda()) + " MT");
            // como utilizei 3 labels diferentes para a descricao, terei que fazer os arranjos abaixo
            String desc = pdao.getOne(id).getDesc();
            if (desc.length() < 46) {
                lblProdutoDesc00.setText(desc);
                lblProdutoDesc01.setText("");
                lblProdutoDesc02.setText("");
            } else if (desc.length() < 91) {
                lblProdutoDesc00.setText(desc.substring(0, 45));
                lblProdutoDesc01.setText(desc.substring(45));
                lblProdutoDesc02.setText("");
                
            } else {
                lblProdutoDesc00.setText(desc.substring(0, 45));
                lblProdutoDesc01.setText(desc.substring(45, 90));
                lblProdutoDesc02.setText(desc.substring(90));
                
            }
        }
    }//GEN-LAST:event_tbProdutoKeyReleased

    private void txtSearchProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchProdutoKeyReleased
        // TODO add your handling code here:
        TableManager tm = new TableManager();
        tm.updateProdutos(tbProduto, txtSearchProduto.getText());
    }//GEN-LAST:event_txtSearchProdutoKeyReleased

    private void btDelProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelProdutoActionPerformed
        // TODO add your handling code here:
        if (tbProduto.getSelectedRow() == -1) {
            //nenhuma linha seleccionada
        } else {
            if (tbProduto.getSelectedRowCount() > 1) {
                // se o utilizador tiver selecionado mais de uma linha
                ProdutoDAO pdao = new ProdutoDAO();
                for (int selectedRow : tbProduto.getSelectedRows()) {
                    int id = Integer.parseInt(tbProduto.getValueAt(selectedRow, 0).toString());
                    pdao.delete(id);
                }
            } else {
                // se tiver sido seleccionada apenas uma linha da tabela
                int id = Integer.parseInt(tbProduto.getValueAt(tbProduto.getSelectedRow(), 0).toString());
                ProdutoDAO pdao = new ProdutoDAO();
                pdao.delete(id);
            }
            // depois de eliminar do banco, actualizo a tabela
            TableManager tm = new TableManager();
            tm.updateProdutos(tbProduto, txtSearchProduto.getText());
        }
    }//GEN-LAST:event_btDelProdutoActionPerformed

    private void btEditProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditProdutoActionPerformed
        // TODO add your handling code here:
        if (tbProduto.getSelectedRow() == -1) {
            // nenhuma linha selecionada
        } else {
            if (tbProduto.getSelectedRowCount() > 1) {
                // mais de um produto selecionado na tabela. nao sera possivel editar
            } else {
                // primeiro vou desativar a tabela para que o utilizador nao altere a linha selecionada, vou precisar do ID nela futuramente
                tbProduto.setEnabled(false);
                PanelManager pm = new PanelManager();
                pm.loadPanel(panelParentProduto, panelCadastroProduto);
                int id = Integer.parseInt(tbProduto.getValueAt(tbProduto.getSelectedRow(), 0).toString());
                ProdutoDAO pdao = new ProdutoDAO();
                txtProduto.setText(pdao.getOne(id).getNome());
                txtDesc.setText(pdao.getOne(id).getDesc());
                txtPrecoGueva.setText(String.valueOf(pdao.getOne(id).getpCompra()));
                txtPrecoVenda.setText(String.valueOf(pdao.getOne(id).getpVenda()));
            }
        }
    }//GEN-LAST:event_btEditProdutoActionPerformed

    private void txtSearchProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadProduto;
    private javax.swing.JButton btCadStock;
    private javax.swing.JButton btCancelProduto;
    private javax.swing.JButton btDelProduto;
    private javax.swing.JButton btEditProduto;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btProduto;
    private javax.swing.JButton btSaveProduto;
    private javax.swing.JButton btStock;
    private javax.swing.JButton btVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBottomLog;
    private javax.swing.JLabel lblImgProduto;
    private javax.swing.JLabel lblLucroStock;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblProdutoDesc00;
    private javax.swing.JLabel lblProdutoDesc01;
    private javax.swing.JLabel lblProdutoDesc02;
    private javax.swing.JLabel lblProdutoPreco;
    private javax.swing.JLabel lblProdutoQtd;
    private javax.swing.JLabel lblQtdProduto;
    private javax.swing.JLabel lblRTStock;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelCadastroProduto;
    private javax.swing.JPanel panelDetalheProduto;
    private javax.swing.JPanel panelDetalheStock;
    private javax.swing.JPanel panelLeftMenu;
    private javax.swing.JPanel panelParent;
    private javax.swing.JPanel panelParentProduto;
    private javax.swing.JPanel panelProduto;
    private javax.swing.JPanel panelStock;
    private javax.swing.JPanel panelStocks;
    private javax.swing.JTable tableStock;
    private javax.swing.JTable tbProduto;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtPrecoGueva;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtProcuraStockProdutos;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtSearchProduto;
    private javax.swing.JTextArea txtStockProdutos;
    // End of variables declaration//GEN-END:variables
}
