/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import helpers.CadastroManager;
import helpers.InputManager;
import helpers.PanelManager;
import helpers.TableManager;
import model.dao.ProdutoDAO;
import model.dao.StockDAO;
import model.dao.VendaDAO;

/**
 *
 * @author horaciocome1
 * estudar como adicionar produto, aumentar/diminuir quantidade
 */
public class Principal extends javax.swing.JFrame {

    
    /**
     * Creates new form Principal
     */
    
    PanelManager panelManager;
    TableManager tableManager;
    ProdutoDAO produtoDAO;
    StockDAO stockDAO;
    VendaDAO vendaDAO;
    CadastroManager cadastroManager;
    InputManager inputManager;
    
    public Principal() {
        this.inputManager = new InputManager();
        this.vendaDAO = new VendaDAO();
        this.stockDAO = new StockDAO();
        this.produtoDAO = new ProdutoDAO();
        this.tableManager = new TableManager();
        this.panelManager = new PanelManager();
        initComponents();
        tableManager.setRowModel(table1_produto);
        tableManager.setRowModel(table1_stock);
        tableManager.setRowModel(table2_stock);
        tableManager.setRowModel(table1_cadStock);
        tableManager.setRowModel(table2_cadStock);
        tableManager.setRowModel(table1_venda);
        tableManager.setRowModel(table2_venda);
        tableManager.setRowModel(table1_cadVenda);
        tableManager.setRowModel(table2_cadVenda);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu_cadStock = new javax.swing.JPopupMenu();
        mitem_add = new javax.swing.JMenuItem();
        panelParent = new javax.swing.JPanel();
        panelProduto = new javax.swing.JPanel();
        txtFiltrar_produto = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        table1_produto = new javax.swing.JTable();
        btNovo_produto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panelCadProduto = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNome_cadProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDesc_cadProduto = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btConfirmar_cadProduto = new javax.swing.JButton();
        btCancelar_cadProduto = new javax.swing.JButton();
        lblErropCompra = new javax.swing.JLabel();
        lblErroNome = new javax.swing.JLabel();
        lblErropVenda = new javax.swing.JLabel();
        ftxtpCompra_cadProduto = new javax.swing.JFormattedTextField();
        ftxtpVenda_cadProduto = new javax.swing.JFormattedTextField();
        panelStock = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        table1_stock = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        table2_stock = new javax.swing.JTable();
        btNovo_stock = new javax.swing.JButton();
        panelCadStock = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1_cadStock = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtFiltrar_cadStock = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        table2_cadStock = new javax.swing.JTable();
        btConfirmar_cadStock = new javax.swing.JButton();
        btCancelar_cadStock = new javax.swing.JButton();
        lblErro_cadStock = new javax.swing.JLabel();
        panelVenda = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        table1_venda = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        table2_venda = new javax.swing.JTable();
        btNovo_venda = new javax.swing.JButton();
        panelCadVenda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1_cadVenda = new javax.swing.JTable();
        txtFiltrar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2_cadVenda = new javax.swing.JTable();
        btCadastrarVenda = new javax.swing.JButton();
        bt_CancelarVenda = new javax.swing.JButton();
        txtOrdenante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbPagamento = new javax.swing.JComboBox<>();
        lblTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mitemProduto = new javax.swing.JMenuItem();
        mitemVenda = new javax.swing.JMenuItem();
        mitemStock = new javax.swing.JMenuItem();

        mitem_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_add_shopping_cart_black_18dp.png"))); // NOI18N
        mitem_add.setToolTipText("Clique aqui para adicionar umaunidade deste produto ao cesto de compras.");
        popupMenu_cadStock.add(mitem_add);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caderninho");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        panelParent.setLayout(new java.awt.CardLayout());

        txtFiltrar_produto.setToolTipText("Filtrar por nome.");

        table1_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "_id", "Produto", "Qtd", "p.Compra", "p.Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1_produto.setToolTipText("Lista dos produtos cadastrados, sua quantidade disponivel, o preco gasto ao comprar cada unidade e o preco para vender cada unidade.");
        table1_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table1_produtoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table1_produtoMouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(table1_produto);
        if (table1_produto.getColumnModel().getColumnCount() > 0) {
            table1_produto.getColumnModel().getColumn(0).setMaxWidth(40);
            table1_produto.getColumnModel().getColumn(1).setResizable(false);
            table1_produto.getColumnModel().getColumn(2).setMaxWidth(64);
            table1_produto.getColumnModel().getColumn(3).setMaxWidth(80);
            table1_produto.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        btNovo_produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_add_black_18dp.png"))); // NOI18N
        btNovo_produto.setToolTipText("Cadastrar um novo produto.");
        btNovo_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo_produtoActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_filter_list_black_18dp.png"))); // NOI18N
        jLabel8.setLabelFor(txtFiltrar_produto);

        javax.swing.GroupLayout panelProdutoLayout = new javax.swing.GroupLayout(panelProduto);
        panelProduto.setLayout(panelProdutoLayout);
        panelProdutoLayout.setHorizontalGroup(
            panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltrar_produto, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btNovo_produto)
                .addGap(18, 18, 18))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelProdutoLayout.setVerticalGroup(
            panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProdutoLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFiltrar_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btNovo_produto))
                .addContainerGap())
        );

        panelParent.add(panelProduto, "card4");

        jLabel4.setLabelFor(txtNome_cadProduto);
        jLabel4.setText("Produto:");

        txtNome_cadProduto.setToolTipText("Preencha com o nome do produto que pretende cadastrar.");
        txtNome_cadProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNome_cadProdutoKeyReleased(evt);
            }
        });

        jLabel5.setLabelFor(txtDesc_cadProduto);
        jLabel5.setText("Descricao:");

        txtDesc_cadProduto.setColumns(20);
        txtDesc_cadProduto.setLineWrap(true);
        txtDesc_cadProduto.setRows(5);
        txtDesc_cadProduto.setToolTipText("Preencha este campo com detalhes do produto. Como por exemplo, tomates que sao vendidos 3 a 3. Ou ainda Arroz que tem seu preco unitario correspondente 2.55Kg.");
        jScrollPane6.setViewportView(txtDesc_cadProduto);

        jLabel6.setText("Preco compra:");

        jLabel7.setText("Preco venda:");

        btConfirmar_cadProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_save_black_18dp.png"))); // NOI18N
        btConfirmar_cadProduto.setToolTipText("Cadastrar este produto ao sistema.");
        btConfirmar_cadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmar_cadProdutoActionPerformed(evt);
            }
        });

        btCancelar_cadProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_clear_black_18dp.png"))); // NOI18N
        btCancelar_cadProduto.setToolTipText("Cancelar cadastro.");
        btCancelar_cadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar_cadProdutoActionPerformed(evt);
            }
        });

        lblErropCompra.setForeground(new java.awt.Color(255, 0, 0));
        lblErropCompra.setText("*");

        lblErroNome.setForeground(new java.awt.Color(255, 0, 0));
        lblErroNome.setText("*");

        lblErropVenda.setForeground(new java.awt.Color(255, 0, 0));
        lblErropVenda.setText("*");

        try {
            ftxtpCompra_cadProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#,###.## MT")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtpCompra_cadProduto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtpCompra_cadProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftxtpCompra_cadProdutoMouseClicked(evt);
            }
        });
        ftxtpCompra_cadProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftxtpCompra_cadProdutoKeyReleased(evt);
            }
        });

        try {
            ftxtpVenda_cadProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#,###.## MT")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtpVenda_cadProduto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtpVenda_cadProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftxtpVenda_cadProdutoMouseClicked(evt);
            }
        });
        ftxtpVenda_cadProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftxtpVenda_cadProdutoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelCadProdutoLayout = new javax.swing.GroupLayout(panelCadProduto);
        panelCadProduto.setLayout(panelCadProdutoLayout);
        panelCadProdutoLayout.setHorizontalGroup(
            panelCadProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome_cadProduto)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadProdutoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCancelar_cadProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConfirmar_cadProduto))
                    .addComponent(jLabel4)
                    .addComponent(lblErroNome)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addGroup(panelCadProdutoLayout.createSequentialGroup()
                        .addGroup(panelCadProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErropCompra)
                            .addComponent(ftxtpCompra_cadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(panelCadProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErropVenda)
                            .addComponent(jLabel7)
                            .addComponent(ftxtpVenda_cadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelCadProdutoLayout.setVerticalGroup(
            panelCadProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome_cadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErroNome)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelCadProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadProdutoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelCadProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtpCompra_cadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxtpVenda_cadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblErropCompra)
                            .addComponent(lblErropVenda))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadProdutoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCadProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btConfirmar_cadProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btCancelar_cadProduto, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        panelParent.add(panelCadProduto, "card5");

        table1_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "_id", "Data Entrada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1_stock.setToolTipText("Lista de stocks ja cadastrados. Clique numa data para saber mais sobre os produtos desse stock e as respectivas quantidades na lista ao lado.");
        jScrollPane7.setViewportView(table1_stock);
        if (table1_stock.getColumnModel().getColumnCount() > 0) {
            table1_stock.getColumnModel().getColumn(0).setMaxWidth(40);
            table1_stock.getColumnModel().getColumn(1).setResizable(false);
        }

        table2_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "_id", "Produto", "Qtd"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2_stock.setToolTipText("Lista com os produtos pertencentes a determvnado stock da lista a esquerda.");
        jScrollPane8.setViewportView(table2_stock);
        if (table2_stock.getColumnModel().getColumnCount() > 0) {
            table2_stock.getColumnModel().getColumn(0).setMaxWidth(40);
            table2_stock.getColumnModel().getColumn(1).setResizable(false);
            table2_stock.getColumnModel().getColumn(2).setMaxWidth(40);
        }

        btNovo_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_add_black_18dp.png"))); // NOI18N
        btNovo_stock.setToolTipText("Registrar um novo stock.");
        btNovo_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo_stockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelStockLayout = new javax.swing.GroupLayout(panelStock);
        panelStock.setLayout(panelStockLayout);
        panelStockLayout.setHorizontalGroup(
            panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStockLayout.createSequentialGroup()
                .addGroup(panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStockLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btNovo_stock))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelStockLayout.setVerticalGroup(
            panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStockLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNovo_stock))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelParent.add(panelStock, "card6");

        table1_cadStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "_id", "Produto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1_cadStock.setToolTipText("Lista de produtos cadastradosactualmente no sistema. Os produtos que se pretende adicionar ao stock devem ser selecionados apartir daqui.");
        table1_cadStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table1_cadStockMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table1_cadStockMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(table1_cadStock);
        if (table1_cadStock.getColumnModel().getColumnCount() > 0) {
            table1_cadStock.getColumnModel().getColumn(0).setMaxWidth(40);
            table1_cadStock.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_filter_list_black_18dp.png"))); // NOI18N
        jLabel2.setLabelFor(txtFiltrar_cadStock);

        txtFiltrar_cadStock.setToolTipText("Filtrar produtos por nome.");

        table2_cadStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "_id", "Produto", "Qtd"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2_cadStock.setToolTipText("Lista com produtos que se pretende inserir no estoque.");
        table2_cadStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table2_cadStockMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table2_cadStockMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(table2_cadStock);
        if (table2_cadStock.getColumnModel().getColumnCount() > 0) {
            table2_cadStock.getColumnModel().getColumn(0).setMaxWidth(40);
            table2_cadStock.getColumnModel().getColumn(1).setResizable(false);
            table2_cadStock.getColumnModel().getColumn(2).setMaxWidth(40);
        }

        btConfirmar_cadStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_save_black_18dp.png"))); // NOI18N
        btConfirmar_cadStock.setToolTipText("Confirmar.");

        btCancelar_cadStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_clear_black_18dp.png"))); // NOI18N
        btCancelar_cadStock.setToolTipText("Cancelar.");
        btCancelar_cadStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar_cadStockActionPerformed(evt);
            }
        });

        lblErro_cadStock.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panelCadStockLayout = new javax.swing.GroupLayout(panelCadStock);
        panelCadStock.setLayout(panelCadStockLayout);
        panelCadStockLayout.setHorizontalGroup(
            panelCadStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadStockLayout.createSequentialGroup()
                .addGroup(panelCadStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCadStockLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltrar_cadStock, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(panelCadStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadStockLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblErro_cadStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(btCancelar_cadStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConfirmar_cadStock)
                        .addContainerGap())
                    .addGroup(panelCadStockLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );
        panelCadStockLayout.setVerticalGroup(
            panelCadStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCadStockLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btConfirmar_cadStock))
                    .addGroup(panelCadStockLayout.createSequentialGroup()
                        .addGroup(panelCadStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(panelCadStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadStockLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCadStockLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelCadStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btCancelar_cadStock, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelCadStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFiltrar_cadStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblErro_cadStock)))))))
                .addContainerGap())
        );

        panelParent.add(panelCadStock, "card3");

        table1_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "_id", "Data", "Total", "Pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(table1_venda);
        if (table1_venda.getColumnModel().getColumnCount() > 0) {
            table1_venda.getColumnModel().getColumn(0).setMaxWidth(40);
            table1_venda.getColumnModel().getColumn(1).setResizable(false);
            table1_venda.getColumnModel().getColumn(2).setMaxWidth(65);
            table1_venda.getColumnModel().getColumn(3).setResizable(false);
            table1_venda.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        table2_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "_id", "Produto", "Qtd"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(table2_venda);
        if (table2_venda.getColumnModel().getColumnCount() > 0) {
            table2_venda.getColumnModel().getColumn(0).setMaxWidth(40);
            table2_venda.getColumnModel().getColumn(1).setResizable(false);
            table2_venda.getColumnModel().getColumn(2).setMaxWidth(40);
        }

        btNovo_venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_add_black_18dp.png"))); // NOI18N
        btNovo_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo_vendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVendaLayout = new javax.swing.GroupLayout(panelVenda);
        panelVenda.setLayout(panelVendaLayout);
        panelVendaLayout.setHorizontalGroup(
            panelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVendaLayout.createSequentialGroup()
                .addGroup(panelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btNovo_venda)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );
        panelVendaLayout.setVerticalGroup(
            panelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVendaLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNovo_venda))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelParent.add(panelVenda, "card7");

        table1_cadVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "_id", "Preco", "Produto", "Qtd"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1_cadVenda.setToolTipText("Esta tabela contem uma lista dos produtos disponiveis, no stock, com seus respectivos precos e quantidades.");
        table1_cadVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table1_cadVendaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table1_cadVendaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table1_cadVenda);
        if (table1_cadVenda.getColumnModel().getColumnCount() > 0) {
            table1_cadVenda.getColumnModel().getColumn(0).setMaxWidth(40);
            table1_cadVenda.getColumnModel().getColumn(1).setMaxWidth(65);
            table1_cadVenda.getColumnModel().getColumn(2).setResizable(false);
            table1_cadVenda.getColumnModel().getColumn(3).setMaxWidth(40);
        }

        txtFiltrar.setToolTipText("Filtrar por nome de produto.");

        table2_cadVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "_id", "Produto", "Qtd"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2_cadVenda.setToolTipText("Esta tabela contem a lista de produtos que o cliente pretende adquirir e a quantidade de cada um que ele pretende adquirir.");
        table2_cadVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table2_cadVendaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table2_cadVendaMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table2_cadVenda);
        if (table2_cadVenda.getColumnModel().getColumnCount() > 0) {
            table2_cadVenda.getColumnModel().getColumn(0).setMaxWidth(40);
            table2_cadVenda.getColumnModel().getColumn(1).setResizable(false);
            table2_cadVenda.getColumnModel().getColumn(2).setMaxWidth(40);
        }

        btCadastrarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_shopping_cart_black_18dp_1.png"))); // NOI18N
        btCadastrarVenda.setToolTipText("Realizar venda.");
        btCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarVendaActionPerformed(evt);
            }
        });

        bt_CancelarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_clear_black_18dp.png"))); // NOI18N
        bt_CancelarVenda.setToolTipText("Anular venda.");
        bt_CancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelarVendaActionPerformed(evt);
            }
        });

        txtOrdenante.setToolTipText("Nome de quem ordena a venda. Obrigatorio em caso de vale.");

        jLabel1.setText("Ordenante:");

        cmbPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modo de pagamento", "Dinheiro", "Vale" }));
        cmbPagamento.setToolTipText("Selecione a forma como sera efectuado o pagamento");

        lblTotal.setText("Total:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_filter_list_black_18dp.png"))); // NOI18N
        jLabel3.setLabelFor(txtFiltrar);

        javax.swing.GroupLayout panelCadVendaLayout = new javax.swing.GroupLayout(panelCadVenda);
        panelCadVenda.setLayout(panelCadVendaLayout);
        panelCadVendaLayout.setHorizontalGroup(
            panelCadVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadVendaLayout.createSequentialGroup()
                .addGroup(panelCadVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCadVendaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
                .addGroup(panelCadVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadVendaLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(panelCadVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal)
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadVendaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(panelCadVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrdenante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadVendaLayout.createSequentialGroup()
                                .addComponent(bt_CancelarVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCadastrarVenda)
                                .addContainerGap())))))
        );
        panelCadVendaLayout.setVerticalGroup(
            panelCadVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadVendaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrdenante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(panelCadVendaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelCadVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCadastrarVenda)
                    .addComponent(bt_CancelarVenda)
                    .addComponent(txtFiltrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelParent.add(panelCadVenda, "card2");

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_menu_black_18dp.png"))); // NOI18N
        menu.setToolTipText("Menu");

        mitemProduto.setText("Produtos");
        mitemProduto.setToolTipText("Para ver os produtos cadastrados ou cadastrar produtos.");
        mitemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemProdutoActionPerformed(evt);
            }
        });
        menu.add(mitemProduto);

        mitemVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_shopping_cart_black_18dp.png"))); // NOI18N
        mitemVenda.setText("Vendas");
        mitemVenda.setToolTipText("Para monvtorar asvendas ou realizar uma venda.");
        mitemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemVendaActionPerformed(evt);
            }
        });
        menu.add(mitemVenda);

        mitemStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_archive_black_18dp.png"))); // NOI18N
        mitemStock.setText("Stocks");
        mitemStock.setToolTipText("Para verificar o stock ou registar um stock.");
        mitemStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemStockActionPerformed(evt);
            }
        });
        menu.add(mitemStock);

        menuBar.add(menu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table1_cadVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1_cadVendaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table1_cadVendaMousePressed

    private void table1_cadVendaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1_cadVendaMouseReleased
        // TODO add your handling code here:
        table1_cadVendaMousePressed(evt);
    }//GEN-LAST:event_table1_cadVendaMouseReleased

    private void table2_cadVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2_cadVendaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table2_cadVendaMousePressed

    private void table2_cadVendaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2_cadVendaMouseReleased
        // TODO add your handling code here:
        table2_cadVendaMousePressed(evt);
    }//GEN-LAST:event_table2_cadVendaMouseReleased

    private void table1_cadStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1_cadStockMousePressed
        // TODO add your handling code here:
        if (evt.isPopupTrigger()) {
            popupMenu_cadStock.show(this, evt.getX(), evt.getY() - 7); // estava a aparecer muito acima
        }
    }//GEN-LAST:event_table1_cadStockMousePressed

    private void table1_cadStockMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1_cadStockMouseReleased
        // TODO add your handling code here:
//        table1_cadStockMousePressed(evt);
    }//GEN-LAST:event_table1_cadStockMouseReleased

    private void table2_cadStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2_cadStockMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table2_cadStockMousePressed

    private void table2_cadStockMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2_cadStockMouseReleased
        // TODO add your handling code here:
        table2_cadStockMousePressed(evt);
    }//GEN-LAST:event_table2_cadStockMouseReleased

    private void table1_produtoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1_produtoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table1_produtoMousePressed

    private void table1_produtoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1_produtoMouseReleased
        // TODO add your handling code here:
        table1_produtoMousePressed(evt);
    }//GEN-LAST:event_table1_produtoMouseReleased

    private void mitemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemProdutoActionPerformed
        // TODO add your handling code here:
        panelManager.loadPanel(panelParent, panelProduto);
        tableManager.preencherTable_produtos(table1_produto, produtoDAO.getAll());
    }//GEN-LAST:event_mitemProdutoActionPerformed

    private void mitemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemVendaActionPerformed
        // TODO add your handling code here:
        panelManager.loadPanel(panelParent, panelVenda);
        tableManager.preencherTable1_venda(table1_venda, vendaDAO.getAll());
    }//GEN-LAST:event_mitemVendaActionPerformed

    private void mitemStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemStockActionPerformed
        // TODO add your handling code here:
        //loadStock();
        panelManager.loadPanel(panelParent, panelStock);
        tableManager.preencherTable1_stock(table1_stock, stockDAO.getAll());
    }//GEN-LAST:event_mitemStockActionPerformed

    private void btNovo_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo_produtoActionPerformed
        // TODO add your handling code here:
        panelManager.loadPanel(panelParent, panelCadProduto);
        cadastroManager = new CadastroManager();
    }//GEN-LAST:event_btNovo_produtoActionPerformed

    private void btCancelar_cadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar_cadProdutoActionPerformed
        // TODO add your handling code here:
        // quando se cancela o cadastro de um produto o cursor volta para a lista de produtos cadastrados
        mitemProdutoActionPerformed(evt);
    }//GEN-LAST:event_btCancelar_cadProdutoActionPerformed

    private void btNovo_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo_stockActionPerformed
        // TODO add your handling code here:
        panelManager.loadPanel(panelParent, panelCadStock);
        tableManager.preencherTable1_cadStock(table1_cadStock, produtoDAO.getAll());
        cadastroManager = new CadastroManager();
    }//GEN-LAST:event_btNovo_stockActionPerformed

    private void btCancelar_cadStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar_cadStockActionPerformed
        // TODO add your handling code here:
        // quando se cancela o o cadastro de um stock o cursor volta para a listas de stocks
        mitemStockActionPerformed(evt);
    }//GEN-LAST:event_btCancelar_cadStockActionPerformed

    private void btNovo_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo_vendaActionPerformed
        // TODO add your handling code here:
        panelManager.loadPanel(panelParent, panelCadVenda);
        tableManager.preencherTable1_cadVenda(table1_venda, produtoDAO.getAll());
        cadastroManager = new CadastroManager();
    }//GEN-LAST:event_btNovo_vendaActionPerformed

    private void bt_CancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelarVendaActionPerformed
        // TODO add your handling code here:
        // quando se cancela uma venda o cursor volta para a lista de vendas
        mitemVendaActionPerformed(evt);
    }//GEN-LAST:event_bt_CancelarVendaActionPerformed

    private void btConfirmar_cadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmar_cadProdutoActionPerformed
        // TODO add your handling code here:
        cadastroManager.cadProduto(txtNome_cadProduto.getText(), txtDesc_cadProduto.getText(),
                inputManager.preco(ftxtpCompra_cadProduto), inputManager.preco(ftxtpVenda_cadProduto),
                lblErroNome, lblErropCompra, lblErropVenda);
    }//GEN-LAST:event_btConfirmar_cadProdutoActionPerformed

    private void txtNome_cadProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNome_cadProdutoKeyReleased
        // TODO add your handling code here:
        inputManager.nomeProduto(txtNome_cadProduto, lblErroNome);
    }//GEN-LAST:event_txtNome_cadProdutoKeyReleased

    private void ftxtpCompra_cadProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtpCompra_cadProdutoKeyReleased
        // TODO add your handling code here:
        inputManager.preco(ftxtpCompra_cadProduto, lblErropCompra);
    }//GEN-LAST:event_ftxtpCompra_cadProdutoKeyReleased

    private void ftxtpVenda_cadProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtpVenda_cadProdutoKeyReleased
        // TODO add your handling code here:
        inputManager.preco(ftxtpVenda_cadProduto, lblErropVenda);
    }//GEN-LAST:event_ftxtpVenda_cadProdutoKeyReleased

    private void ftxtpCompra_cadProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftxtpCompra_cadProdutoMouseClicked
        // TODO add your handling code here:
        inputManager.preco(ftxtpCompra_cadProduto, lblErropCompra);
    }//GEN-LAST:event_ftxtpCompra_cadProdutoMouseClicked

    private void ftxtpVenda_cadProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftxtpVenda_cadProdutoMouseClicked
        // TODO add your handling code here:
        inputManager.preco(ftxtpVenda_cadProduto, lblErropVenda);
    }//GEN-LAST:event_ftxtpVenda_cadProdutoMouseClicked

    private void btCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarVendaActionPerformed
        // TODO add your handling code here:
        cadastroManager.cadVenda(String.valueOf(cmbPagamento.getSelectedItem()), txtOrdenante.getText());
    }//GEN-LAST:event_btCadastrarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarVenda;
    private javax.swing.JButton btCancelar_cadProduto;
    private javax.swing.JButton btCancelar_cadStock;
    private javax.swing.JButton btConfirmar_cadProduto;
    private javax.swing.JButton btConfirmar_cadStock;
    private javax.swing.JButton btNovo_produto;
    private javax.swing.JButton btNovo_stock;
    private javax.swing.JButton btNovo_venda;
    private javax.swing.JButton bt_CancelarVenda;
    private javax.swing.JComboBox<String> cmbPagamento;
    private javax.swing.JFormattedTextField ftxtpCompra_cadProduto;
    private javax.swing.JFormattedTextField ftxtpVenda_cadProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblErroNome;
    private javax.swing.JLabel lblErro_cadStock;
    private javax.swing.JLabel lblErropCompra;
    private javax.swing.JLabel lblErropVenda;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mitemProduto;
    private javax.swing.JMenuItem mitemStock;
    private javax.swing.JMenuItem mitemVenda;
    private javax.swing.JMenuItem mitem_add;
    private javax.swing.JPanel panelCadProduto;
    private javax.swing.JPanel panelCadStock;
    private javax.swing.JPanel panelCadVenda;
    private javax.swing.JPanel panelParent;
    private javax.swing.JPanel panelProduto;
    private javax.swing.JPanel panelStock;
    private javax.swing.JPanel panelVenda;
    private javax.swing.JPopupMenu popupMenu_cadStock;
    private javax.swing.JTable table1_cadStock;
    private javax.swing.JTable table1_cadVenda;
    private javax.swing.JTable table1_produto;
    private javax.swing.JTable table1_stock;
    private javax.swing.JTable table1_venda;
    private javax.swing.JTable table2_cadStock;
    private javax.swing.JTable table2_cadVenda;
    private javax.swing.JTable table2_stock;
    private javax.swing.JTable table2_venda;
    private javax.swing.JTextArea txtDesc_cadProduto;
    private javax.swing.JTextField txtFiltrar;
    private javax.swing.JTextField txtFiltrar_cadStock;
    private javax.swing.JTextField txtFiltrar_produto;
    private javax.swing.JTextField txtNome_cadProduto;
    private javax.swing.JTextField txtOrdenante;
    // End of variables declaration//GEN-END:variables
}
