/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import helpers.TableManager;
import java.util.ArrayList;
import java.util.List;
import model.bean.Produto;

/**
 *
 * @author horaciocome1
 */
public class ProdutoSelector extends javax.swing.JFrame {
    
    List<Produto> produtos;

    /**
     * Creates new form ProdutoSelector
     */
    public ProdutoSelector() {
        initComponents();
        // carrega os produtos cadastrados no banco para a tabela a esquarda
        new TableManager().updateProdutos(tableCadastrados, txtPesquisa.getText());
        // instancia a lista
        produtos = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCadastrados = new javax.swing.JTable();
        btInc = new javax.swing.JButton();
        btDec = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSeleccionados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Seleccionador de Produtos");
        setAlwaysOnTop(true);
        setResizable(false);

        tableCadastrados.setBackground(new java.awt.Color(241, 241, 241));
        tableCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Produto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCadastrados.setGridColor(new java.awt.Color(213, 213, 213));
        tableCadastrados.setShowVerticalLines(false);
        tableCadastrados.getTableHeader().setResizingAllowed(false);
        tableCadastrados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableCadastrados);
        if (tableCadastrados.getColumnModel().getColumnCount() > 0) {
            tableCadastrados.getColumnModel().getColumn(0).setMaxWidth(60);
            tableCadastrados.getColumnModel().getColumn(1).setResizable(false);
        }

        btInc.setText(">>");
        btInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncActionPerformed(evt);
            }
        });

        btDec.setText("<<");

        tableSeleccionados.setBackground(new java.awt.Color(241, 241, 241));
        tableSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Produto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSeleccionados.setGridColor(new java.awt.Color(213, 213, 213));
        tableSeleccionados.setShowVerticalLines(false);
        tableSeleccionados.getTableHeader().setResizingAllowed(false);
        tableSeleccionados.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableSeleccionados);
        if (tableSeleccionados.getColumnModel().getColumnCount() > 0) {
            tableSeleccionados.getColumnModel().getColumn(0).setMaxWidth(60);
            tableSeleccionados.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_search_black_18dp.png"))); // NOI18N

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        btClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_chevron_left_black_18dp.png"))); // NOI18N
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(82, 82, 82));
        jLabel2.setText("*Seleccione dentre os produtos a esquerda.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btClose))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btInc)
                                    .addComponent(btDec, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btInc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDec)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btClose)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        // TODO add your handling code here:
        // fecha a janela
        this.dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    private void btIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncActionPerformed
        // TODO add your handling code here:
        if(tableCadastrados.getSelectedRow() == -1) {
            // nenhuma linha seleccionada
        } else {
            // alguma linha selecionada
            if (tableCadastrados.getSelectedRowCount() > 1) {
                // para varias linhas seleccionadas, de momento nao sera implementado
            } else {
                // somente uma linha seleccionada
                Produto p = new Produto();
                p.setId((int) tableCadastrados.getValueAt(tableCadastrados.getSelectedRow(), 0));
                p.setNome((String) tableCadastrados.getValueAt(tableCadastrados.getSelectedRow(), 1));
                // o produto eh adicionado a lista
                produtos.add(p);
                // de seguida o produto vai para tabela a direita
                new TableManager().rowModel(tableSeleccionados).addRow(new Object[]{p.getId(), p.getNome()});
            }
        }
    }//GEN-LAST:event_btIncActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:
        new TableManager().updateProdutos(tableCadastrados, txtPesquisa.getText());
    }//GEN-LAST:event_txtPesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoSelector.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoSelector.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoSelector.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoSelector.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDec;
    private javax.swing.JButton btInc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCadastrados;
    private javax.swing.JTable tableSeleccionados;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
